version: '3.8'

services:
  # Jupyter Notebook/Lab service
  jupyter:
    build: .
    container_name: kaggle_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/data
      - ./workspace:/home/jovyan/workspace
      - ./mlruns:/home/jovyan/mlruns
      - ./wandb:/home/jovyan/wandb
    working_dir: /home/jovyan/workspace
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - WANDB_DIR=/home/jovyan/wandb
      - JUPYTER_TOKEN=kaggle
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=kaggle
    networks:
      - kaggle_network

  # MLflow Tracking Server service with MySQL backend
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: kaggle_mlflow
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/home/mlflow/mlruns
    depends_on:
      mlflow_mysql:
        condition: service_healthy
    command: >
      mlflow ui
      --backend-store-uri mysql+pymysql://mlflow:mlflow@mlflow_mysql:3306/mlflow
      --default-artifact-root /home/mlflow/mlruns
      --host 0.0.0.0
    networks:
      - kaggle_network


  # MySQL database for MLflow
  mlflow_mysql:
    image: mysql:8.0
    container_name: mlflow_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mlflow_root
      - MYSQL_DATABASE=mlflow
      - MYSQL_USER=mlflow
      - MYSQL_PASSWORD=mlflow
    volumes:
      - mlflow_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kaggle_network

  # MySQL database for W&B
  mysql:
    image: mysql:5.7
    container_name: kaggle_mysql
    environment:
      - MYSQL_DATABASE=wandb_local
      - MYSQL_USER=wandb_local
      - MYSQL_PASSWORD=wandb_local
      - MYSQL_ROOT_PASSWORD=wandb_local
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kaggle_network

  # Weights & Biases Local Server
  wandb:
    image: wandb/local:latest
    container_name: kaggle_wandb
    ports:
      - "8082:8080"
    environment:
      - WANDB_LOCAL=true
      - NODE_ENV=development
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=wandb_local
      - MYSQL_USER=wandb_local
      - MYSQL_PASSWORD=wandb_local
      - HOST=http://localhost:8082
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8080
      - PUBLIC_URL=http://localhost:8082
      - BASE_URL=http://localhost:8082
      - GORILLA_BASE_URL=http://localhost:8082
      - WEAVE_URL=http://localhost:8082
      - LOCAL_RESTORE=true
    volumes:
      - wandb_data:/vol
    depends_on:
      mysql:
        condition: service_healthy
    command: "/usr/sbin/my_init"
    networks:
      - kaggle_network

# Networks for inter-service communication
networks:
  kaggle_network:
    driver: bridge

# Persistent volumes for databases and data storage
volumes:
  mysql_data:
  wandb_data:
  mlflow_mysql_data:
